name: Deploy Tael App
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to App Engine
      id: deploy  
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_SA_KEY }}
        promote: false
        version: v1
