name: Deploy Tael App
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load Config Files
        run: | 
          echo ${{secrets.CONFIG}} | base64 --decode > config/config.env
          echo ${{secrets.BUCKET}} | base64 --decode > config/tael-313422-f0de8e38a314.json
          cat  config/tael-313422-f0de8e38a314.json
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{secrets.GCP_PROJECT}}
          service_account_key: ${{secrets.GCP_SA_KEY}}
      - name: Deploy to App Engine  
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: false
          version: v2
  
